export enum GLOBAL_CRON_EVENTS {
  HANDLE_BOOKINGS = 'HANDLE_BOOKINGS',
  HANDLE_PAYMENT_APPROACH = 'HANDLE_PAYMENT_APPROACH',
  HANDLE_TRIALS = 'HANDLE_TRIALS',
  HANDLE_TRIAL_APPROACH = 'HANDLE_TRIAL_APPROACH',
  HANDLE_PAYMENTS = 'HANDLE_PAYMENTS',
}
